[package]
name = "enm_watcher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.11.13"
scraper = "0.13.0"
tokio = { version = "1.22.0", features = ["full"] }